### ISSUE TITLE
HTTPS beacon error

### ISSUE THREAD

**Issue by lz520520** [darkr4y/geacon#4]
If it is https beacon, httpRequest.Post and httpRequest.Post will report an error indicating that the SSL certificate is invalid. But this problem has been solved, just add an init() function to http.go and set "httpRequest.EnableInsecureTLS(true)"

**Comment by darkr4y** [comment]
The reason for not directly ignoring the certificate error is that c2profile is not currently supported, whether or not to validate the certificate is controlled by c2profile's [https-certificate](https://www.cobaltstrike.com/help-malleable-c2) option, currently I push a simple code to give the option to ignore whether the certificate is valid or not, as you suggested.
This feature will be improved in the future.

**Comment by lz520520** [comment]
right,but there is no need to check the validity of the certificate for cs. In addition, I also found a few problems
1. In order to prevent the ComputerName from being too long, a length limit of 10 will cause some names to be displayed incompletely. I suggest to set a ComputerNameLength in config.go with an initial value of 0, call MakeMetaInfo to calculate the length of the first payload, and then get Actual biggest
ComputerNameLength=pub.Size()-len(MakeMetaInfo())-11,
after updating ComputerNameLength, the full name can be obtained in most cases.
2. The online hosts all display x86. This is because " if else if " is used in the function GetMetaDataFlag to judge, but each condition should be superimposed, and a separate " if" should be used to judge.
When making this suggestion, in fact, I have already modified it. Does the author intend to optimize

**Comment by darkr4y** [comment]
Thanks again for the advice, and since I don't have a lot of time to focus on this project, all PR is very welcome!

**Comment by darkr4y** [comment]
the issue will be closed,you can reopen it whenever you want.

**Comment by darkr4y** [comment]
the issue will be closed,you can reopen it whenever you want.
