### ISSUE TITLE
Public usage

### ISSUE THREAD

**Issue by silascutler** [darkr4y/geacon#5]
https://blog.netlab.360.com/blackrota-an-obfuscated-backdoor-written-in-go-en/

**Comment by darkr4y** [comment]
😞 
It's a shame to see a research project being used for a bad thing, although I've reiterated many times that it shouldn't be used for illegal purposes, and maybe I'll close this project in the near future.

Thank you for your reminder :)

**Comment by reanimat0r** [comment]
> 😞
> It's a shame to see a research project being used for a bad thing, although I've reiterated many times that it shouldn't be used for illegal purposes, and maybe I'll close this project in the near future.
> 
> Thank you for your reminder :)

Your project does far more good than harm. Please don't close it. 
🙏
