### ISSUE TITLE
How to compile on Linux?

### ISSUE THREAD

**Issue by useragent23253** [darkr4y/geacon#7]
Hello can u provide some instructions how to compile BeaconTool.jar from sources?

-[~/Desktop/Github/geacon]
└─$ mvn compile
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.043 s
[INFO] Finished at: 2023-01-26T01:12:04-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/host/Desktop/Github/geacon). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by darkr4y** [comment]
Please learn how to build a project using mvn first!
